name: Patch compose-unpacker and Build Docker Image

inputs:
  portainer_tag:
    type: string
    description: The Portainer tag to base the image on
    required: true
  image_tag:
    type: string
    description: The tag for the built Docker image
    required: true
  push:
    type: boolean
    description: Whether to push the built image to the registry
    default: false

runs:
  using: composite

  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Patch compose-unpacker
      run: ./patch.sh ${{ inputs.portainer_tag }}
      shell: bash

    - name: Determine Go version
      id: go-version
      run: |
        # Determine the go version from the go.mod file
        GO_VERSION=$(grep -oP 'go \K([0-9]+\.?)+' "./packages/compose-unpacker/go.mod")
        if [ -z "${GO_VERSION}" ]; then
          echo "Could not determine Go version from go.mod"
          exit 1
        fi
        echo go_version="${GO_VERSION}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        build-args: |
          GO_VERSION="${{ steps.go-version.outputs.go_version }}"
          PORTAINER_TAG="${{ inputs.portainer_tag }}"
        push: ${{ inputs.push }}
        tags: ${{ inputs.image_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
