name: Check Portainer Releases

on:
  schedule:
    # Not too frequently, catch new releases eventually
    - cron: '0 0 */14 * *'
  workflow_dispatch:

jobs:
  check-releases:
    runs-on: ubuntu-latest
    outputs:
      unpatched_releases: ${{ steps.unpatched-releases.outputs.releases }}
      has_unpatched_releases: ${{ steps.unpatched-releases.outputs.found }}
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Find unpatched releases
        id: unpatched-releases
        run: ./check_releases.sh
        env:
          GH_TOKEN: ${{ github.token }}

  create-issues:
    needs: check-releases
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    strategy:
      matrix:
        release: ${{ fromJson(needs.check-releases.outputs.unpatched_releases) }}
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Find issue for release
        id: find-issue
        run: |
          number=$(gh issue list \
            --search "Portainer ${{ matrix.release }}" \
            --state all \
            --label "unpatched release" \
            --json number \
            --jq '.[0].number')
          echo "issue_number=${number}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Report existing issue
        run: |
          issue_link=$(gh issue view ${{ steps.find-issue.outputs.issue_number }} --json url --jq '.url')
          echo "**Existing issue for Portainer ${{ matrix.release }}**: ${issue_link}" >> $GITHUB_STEP_SUMMARY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.find-issue.outputs.issue_number != ''

      - name: Attempt patch & build
        id: patch-build
        uses: ./.github/actions/patch-build
        with:
          portainer_tag: ${{ matrix.release }}
          image_tag: ${{ matrix.release }}-test
        continue-on-error: true
        if: steps.find-issue.outputs.issue_number == ''

      - name: Create issue for unpatched release
        run: |
          release="${{ matrix.release }}" \
            outcome="${{ steps.patch-build.outcome }}" \
            repository=${{ github.repository }} \
            run_id=${{ github.run_id }} \
            envsubst < .github/release-issue-body.md > issue.md
          issue_link=$(
            gh issue create \
              --title "Release a patched version for Portainer ${{ matrix.release }}" \
              --body-file issue.md \
              --label "unpatched release"
          )
          echo "**Build result for Portainer ${{ matrix.release }}**: `${{ steps.patch-build.outcome }}`" >> $GITHUB_STEP_SUMMARY
          echo "**Created issue for Portainer ${{ matrix.release }}**: ${issue_link}" >> $GITHUB_STEP_SUMMARY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.find-issue.outputs.issue_number == ''

    if: needs.check-releases.outputs.has_unpatched_releases == 'true'
