name: Release

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Patch compose-unpacker and Build Docker Image
        uses: ./.github/actions/patch-build
        with:
          portainer_tag: ${{ github.event.release.tag_name }}
          image_tag: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          push: true
